apiVersion: batch/v1
kind: CronJob
metadata:
  name: psconf-weather-demo
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: pvc-weather
          containers:
          - name: apitest
            image: ghcr.io/roberthstrand/psconf23:main
            imagePullPolicy: Always
            command:
            - "pwsh"
            - "-File"
            - "weather.ps1"
            - "-Fetch"
            volumeMounts:
            - name: data
              mountPath: /data
            env:
            - name: OPENWEATHERMAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openweather
                  key: token
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-weather
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-weather
spec:
  volumeName: pv-weather
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---